version: "2"
exclude_patterns:
  - "node_modules/"
  - "test/"
  - "tests/"
  - "*.config.js"

engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - typescript

ratings:
  paths:
    - "otp-service/**/*"
